--Parte 1
CREATE TABLESPACE mid_term
DATAFILE 'mid_term.dbf' SIZE 50M;

CREATE USER dbarrientos 
	IDENTIFIED BY dbarrientos 	
	DEFAULT TABLESPACE mid_term 	
	QUOTA UNLIMITED  ON mid_term;

CREATE ROLE MINI_DBA;
CREATE ROLE STUDENT;

GRANT CREATE TABLE, CREATE SEQUENCE, ON  MINI_DBA;

GRANT CREATE SESSION, ON STUDENT TO MINI_DBA;

GRAN SELECT, INSERT, DELETE, UPDATE ON scott.dept TO miROLE;
GRAN SELECT ON scott.dept TO miROLE;
